
modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="GNU General Public License v3.0"
issueTrackerURL="https://github.com/ISenseHostility/Food-Enhancements/issues"

[[mods]] #mandatory
    modId="food_enhancements" #mandatory
    version="1.16.5-1.5.0" #mandatory
    displayName="Food Enhancements" #mandatory
    displayURL="https://www.curseforge.com/minecraft/mc-mods/food-enhancements"
    logoFile="food_enhancements.png" #optional
    authors="ISenseHostility" #optional
    description='''
    Food Enhancements adds some vanilla-friendly foods to the game!
    '''

[[dependencies.food_enhancements]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.food_enhancements]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"
